<a href="https://colab.research.google.com/github/manojvp16/Ai-Engineer/blob/main/pandastutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [133]:
import pandas as pd

In [134]:
s=pd.Series([10,20,30,40,50,60])
s

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [135]:
s.dtype

dtype('int64')

In [136]:
s.values

array([10, 20, 30, 40, 50, 60])

In [137]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [138]:
s.name="numbers"

In [139]:
s

0    10
1    20
2    30
3    40
4    50
5    60
Name: numbers, dtype: int64

In [140]:
s.name

'numbers'

In [141]:
s[0]

np.int64(10)

In [142]:
s[0:2]

0    10
1    20
Name: numbers, dtype: int64

In [143]:
s[2:4]

2    30
3    40
Name: numbers, dtype: int64

In [144]:
s.iloc[:]

0    10
1    20
2    30
3    40
4    50
5    60
Name: numbers, dtype: int64

In [145]:
s.iloc[0]

np.int64(10)

In [146]:
s.iloc[[1,3,4]]

1    20
3    40
4    50
Name: numbers, dtype: int64

In [147]:
s.name

'numbers'

In [148]:
s.name="calories"

In [149]:
s.name

'calories'

In [150]:
index=["apple","orange","banana","kiwi","mango","lime"]

In [151]:
index

['apple', 'orange', 'banana', 'kiwi', 'mango', 'lime']

In [152]:
s.index=index

In [153]:
s

apple     10
orange    20
banana    30
kiwi      40
mango     50
lime      60
Name: calories, dtype: int64

iloc and loc

In [154]:
# iloc only works with numberical value
# s.iloc["apple"]- doesn't work

In [155]:
# so we have loc -  which is used with label based indexing
# in lable indexing neeed both start and end index

In [156]:
s.loc["apple"]

np.int64(10)

In [157]:
s.loc['apple':'kiwi']

apple     10
orange    20
banana    30
kiwi      40
Name: calories, dtype: int64

In [158]:
fruit_protein = {
    "apple": 0.3,
    "banana": 1.3,
    "grapes": 0.6,
    "orange": 0.9,
    "mango": 0.8,
}

In [159]:
s2=pd.Series(fruit_protein,name="Protein")

In [160]:
s2

apple     0.3
banana    1.3
grapes    0.6
orange    0.9
mango     0.8
Name: Protein, dtype: float64

Conditional Selection

In [161]:
s2>0.7

apple     False
banana     True
grapes    False
orange     True
mango      True
Name: Protein, dtype: bool

**Logical Operator and, or and not**

In [162]:
s2[(s2>0.5) & (s2<1)]

grapes    0.6
orange    0.9
mango     0.8
Name: Protein, dtype: float64

In [163]:
s2[(s2>0.5) | (s2<1)]

apple     0.3
banana    1.3
grapes    0.6
orange    0.9
mango     0.8
Name: Protein, dtype: float64

In [164]:
s2[~(s2<1)]

banana    1.3
Name: Protein, dtype: float64

### DataFrames

In [165]:
import numpy as np

In [166]:
data = {
    "name": ["Alice", "Bob", "Charlie", "David", "Eva", "Alice"],
    "age": [25, 30, 35, np.nan, 29, 25],
    "department": ["HR", "IT", "Finance", "HR", "IT", "HR"],
    "salary": [50000, 60000, 70000, 52000, np.nan, 50000],
}

In [167]:
df=pd.DataFrame(data)

In [168]:
df

      name   age department   salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         HR  52000.0
4      Eva  29.0         IT      NaN
5    Alice  25.0         HR  50000.0

In [169]:
# accessing row from top
df.head(2)

    name   age department   salary
0  Alice  25.0         HR  50000.0
1    Bob  30.0         IT  60000.0

In [170]:
# accessing element from bottom
df.tail(2)

    name   age department   salary
4    Eva  29.0         IT      NaN
5  Alice  25.0         HR  50000.0

In [171]:
# loc and iloc

In [172]:
df.iloc[1:3]

      name   age department   salary
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0

In [173]:
df.loc[1:3,["age","department"]]

    age department
1  30.0         IT
2  35.0    Finance
3   NaN         HR

In [174]:
df.loc[:,["age","department"]]

    age department
0  25.0         HR
1  30.0         IT
2  35.0    Finance
3   NaN         HR
4  29.0         IT
5  25.0         HR

In [175]:
df.iloc[:]

      name   age department   salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         HR  52000.0
4      Eva  29.0         IT      NaN
5    Alice  25.0         HR  50000.0

In [176]:
df.iloc[:,:2]

      name   age
0    Alice  25.0
1      Bob  30.0
2  Charlie  35.0
3    David   NaN
4      Eva  29.0
5    Alice  25.0

In [177]:
df["age"]

0    25.0
1    30.0
2    35.0
3     NaN
4    29.0
5    25.0
Name: age, dtype: float64

In [178]:
df.drop("age",axis=1)

      name department   salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance  70000.0
3    David         HR  52000.0
4      Eva         IT      NaN
5    Alice         HR  50000.0

In [179]:
df

      name   age department   salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         HR  52000.0
4      Eva  29.0         IT      NaN
5    Alice  25.0         HR  50000.0

In [180]:
# as u saw we deleted the age colunm but its still there
# for to permentry delete it u neeed inplace=True this will delete

In [181]:
# df.drop("age",axis=1, inplace=True)
df.drop("age",axis=1)

      name department   salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance  70000.0
3    David         HR  52000.0
4      Eva         IT      NaN
5    Alice         HR  50000.0

In [182]:
df

      name   age department   salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         HR  52000.0
4      Eva  29.0         IT      NaN
5    Alice  25.0         HR  50000.0

In [183]:
df.shape

(6, 4)

In [184]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        6 non-null      object
 1   age         5 non-null      float64
 2   department  6 non-null      object
 3   salary      5 non-null      float64
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes

In [185]:
df.describe()

             age        salary
count   5.000000      5.000000
mean   28.800000  56400.000000
std     4.147288   8648.699324
min    25.000000  50000.000000
25%    25.000000  50000.000000
50%    29.000000  52000.000000
75%    30.000000  60000.000000
max    35.000000  70000.000000

### Broadcasting

In [186]:
df["salary"] = df["salary"] + 5000

In [187]:
df["salary"]

0    55000.0
1    65000.0
2    75000.0
3    57000.0
4        NaN
5    55000.0
Name: salary, dtype: float64

In [188]:
# rename columns

In [189]:
df

      name   age department   salary
0    Alice  25.0         HR  55000.0
1      Bob  30.0         IT  65000.0
2  Charlie  35.0    Finance  75000.0
3    David   NaN         HR  57000.0
4      Eva  29.0         IT      NaN
5    Alice  25.0         HR  55000.0

In [190]:
df.rename(columns={"department": "dept"},inplace=True)

In [191]:
df

      name   age     dept   salary
0    Alice  25.0       HR  55000.0
1      Bob  30.0       IT  65000.0
2  Charlie  35.0  Finance  75000.0
3    David   NaN       HR  57000.0
4      Eva  29.0       IT      NaN
5    Alice  25.0       HR  55000.0

In [192]:
df["dept"].unique()

array(['HR', 'IT', 'Finance'], dtype=object)

In [193]:
df["dept"].value_counts()

dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [194]:
df["promoted salary"] = df["salary"] * 8

In [195]:
df

      name   age     dept   salary  promoted salary
0    Alice  25.0       HR  55000.0         440000.0
1      Bob  30.0       IT  65000.0         520000.0
2  Charlie  35.0  Finance  75000.0         600000.0
3    David   NaN       HR  57000.0         456000.0
4      Eva  29.0       IT      NaN              NaN
5    Alice  25.0       HR  55000.0         440000.0

### Data Cleaning

Missing Values

In [196]:
df.isnull()

    name    age   dept  salary  promoted salary
0  False  False  False   False            False
1  False  False  False   False            False
2  False  False  False   False            False
3  False   True  False   False            False
4  False  False  False    True             True
5  False  False  False   False            False

In [197]:
df.isnull().sum()

name               0
age                1
dept               0
salary             1
promoted salary    1
dtype: int64

In [198]:
# df.dropna() this will remove rows which has nul values

In [199]:
# df.dropna(how='any') by default-any row witl any null value

In [200]:
# df.dropna(how='all') remove row if there is any null value

In [201]:
# if i want to fill all nan value with 0
df.fillna(0)

      name   age     dept   salary  promoted salary
0    Alice  25.0       HR  55000.0         440000.0
1      Bob  30.0       IT  65000.0         520000.0
2  Charlie  35.0  Finance  75000.0         600000.0
3    David   0.0       HR  57000.0         456000.0
4      Eva  29.0       IT      0.0              0.0
5    Alice  25.0       HR  55000.0         440000.0

In [202]:
df

      name   age     dept   salary  promoted salary
0    Alice  25.0       HR  55000.0         440000.0
1      Bob  30.0       IT  65000.0         520000.0
2  Charlie  35.0  Finance  75000.0         600000.0
3    David   NaN       HR  57000.0         456000.0
4      Eva  29.0       IT      NaN              NaN
5    Alice  25.0       HR  55000.0         440000.0

In [203]:
df["age"].fillna(df["age"].mean())

0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: age, dtype: float64

In [204]:
df["salary"].fillna(df["salary"].mean())

0    55000.0
1    65000.0
2    75000.0
3    57000.0
4    61400.0
5    55000.0
Name: salary, dtype: float64

In [205]:
df["salary"].fillna(df["salary"].median())

0    55000.0
1    65000.0
2    75000.0
3    57000.0
4    57000.0
5    55000.0
Name: salary, dtype: float64

In [206]:
df["age"].fillna(method = 'ffill')

/tmp/ipykernel_709/2073767450.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["age"].fillna(method = 'ffill')

0    25.0
1    30.0
2    35.0
3    35.0
4    29.0
5    25.0
Name: age, dtype: float64

In [207]:
df["age"].fillna(method = 'bfill')

/tmp/ipykernel_709/2571892657.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["age"].fillna(method = 'bfill')

0    25.0
1    30.0
2    35.0
3    29.0
4    29.0
5    25.0
Name: age, dtype: float64

In [208]:
df["age"].ffill()

0    25.0
1    30.0
2    35.0
3    35.0
4    29.0
5    25.0
Name: age, dtype: float64

In [209]:
df["age"].bfill()

0    25.0
1    30.0
2    35.0
3    29.0
4    29.0
5    25.0
Name: age, dtype: float64

In [210]:
df

      name   age     dept   salary  promoted salary
0    Alice  25.0       HR  55000.0         440000.0
1      Bob  30.0       IT  65000.0         520000.0
2  Charlie  35.0  Finance  75000.0         600000.0
3    David   NaN       HR  57000.0         456000.0
4      Eva  29.0       IT      NaN              NaN
5    Alice  25.0       HR  55000.0         440000.0

In [211]:
df["name"].replace("Charlie","maddy")

0    Alice
1      Bob
2    maddy
3    David
4      Eva
5    Alice
Name: name, dtype: object

In [212]:
df["name"]=df["name"].replace("Charlie","maddy")

In [213]:
df

    name   age     dept   salary  promoted salary
0  Alice  25.0       HR  55000.0         440000.0
1    Bob  30.0       IT  65000.0         520000.0
2  maddy  35.0  Finance  75000.0         600000.0
3  David   NaN       HR  57000.0         456000.0
4    Eva  29.0       IT      NaN              NaN
5  Alice  25.0       HR  55000.0         440000.0

Duplicate Values

In [214]:
df_dup=df[df.duplicated]

In [215]:
df_dup

    name   age dept   salary  promoted salary
5  Alice  25.0   HR  55000.0         440000.0

In [216]:
df[df.duplicated(keep='first')]
# df[df.duplicated(keep='last')]

    name   age dept   salary  promoted salary
5  Alice  25.0   HR  55000.0         440000.0

In [217]:
df=df.drop_duplicates()

In [218]:
df

    name   age     dept   salary  promoted salary
0  Alice  25.0       HR  55000.0         440000.0
1    Bob  30.0       IT  65000.0         520000.0
2  maddy  35.0  Finance  75000.0         600000.0
3  David   NaN       HR  57000.0         456000.0
4    Eva  29.0       IT      NaN              NaN

In [219]:
df = df.rename(columns={"promoted salary": "promoted_salary"})

In [220]:
df

    name   age     dept   salary  promoted_salary
0  Alice  25.0       HR  55000.0         440000.0
1    Bob  30.0       IT  65000.0         520000.0
2  maddy  35.0  Finance  75000.0         600000.0
3  David   NaN       HR  57000.0         456000.0
4    Eva  29.0       IT      NaN              NaN

### Lambda

In [221]:
# invalid value

In [223]:
df["promoted_salary"] = df["promoted_salary"].apply(lambda x: x / 10 if x > 650000 else x)

In [224]:
df

    name   age     dept   salary  promoted_salary
0  Alice  25.0       HR  55000.0         440000.0
1    Bob  30.0       IT  65000.0         520000.0
2  maddy  35.0  Finance  75000.0         600000.0
3  David   NaN       HR  57000.0         456000.0
4    Eva  29.0       IT      NaN              NaN

In [225]:
def multiply_age(x):
    return x * 2


df["age"] = df["age"].apply(multiply_age)

In [226]:
df

    name   age     dept   salary  promoted_salary
0  Alice  50.0       HR  55000.0         440000.0
1    Bob  60.0       IT  65000.0         520000.0
2  maddy  70.0  Finance  75000.0         600000.0
3  David   NaN       HR  57000.0         456000.0
4    Eva  58.0       IT      NaN              NaN

In [227]:
df["age"] = df["age"].apply(lambda x: x / 2)

In [228]:
df

    name   age     dept   salary  promoted_salary
0  Alice  25.0       HR  55000.0         440000.0
1    Bob  30.0       IT  65000.0         520000.0
2  maddy  35.0  Finance  75000.0         600000.0
3  David   NaN       HR  57000.0         456000.0
4    Eva  29.0       IT      NaN              NaN

### Concat & Merge

In [236]:
df2_data = {
    "dept": ["HR", "IT", "Finance"],
    "location": ["New York", "San Francisco", "Chicago"],
    "manager": ["Laura", "Steve", "David"],
}

In [237]:
df2 = pd.DataFrame(df2_data)

In [238]:
print(pd.concat([df, df2], axis=0))  # Row-wise concatenation

    name   age     dept   salary  promoted_salary       location manager
0  Alice  25.0       HR  55000.0         440000.0            NaN     NaN
1    Bob  30.0       IT  65000.0         520000.0            NaN     NaN
2  maddy  35.0  Finance  75000.0         600000.0            NaN     NaN
3  David   NaN       HR  57000.0         456000.0            NaN     NaN
4    Eva  29.0       IT      NaN              NaN            NaN     NaN
0    NaN   NaN       HR      NaN              NaN       New York   Laura
1    NaN   NaN       IT      NaN              NaN  San Francisco   Steve
2    NaN   NaN  Finance      NaN              NaN        Chicago   David

In [239]:
print(pd.concat([df, df2], axis=1))  # Column-wise concatenation [01:00:33]

    name   age     dept   salary  promoted_salary     dept       location  \
0  Alice  25.0       HR  55000.0         440000.0       HR       New York
1    Bob  30.0       IT  65000.0         520000.0       IT  San Francisco
2  maddy  35.0  Finance  75000.0         600000.0  Finance        Chicago
3  David   NaN       HR  57000.0         456000.0      NaN            NaN
4    Eva  29.0       IT      NaN              NaN      NaN            NaN

  manager
0   Laura
1   Steve
2   David
3     NaN
4     NaN

In [240]:
merged_df = pd.merge(df, df2, on="dept")

In [241]:
merged_df

    name   age     dept   salary  promoted_salary       location manager
0  Alice  25.0       HR  55000.0         440000.0       New York   Laura
1    Bob  30.0       IT  65000.0         520000.0  San Francisco   Steve
2  maddy  35.0  Finance  75000.0         600000.0        Chicago   David
3  David   NaN       HR  57000.0         456000.0       New York   Laura
4    Eva  29.0       IT      NaN              NaN  San Francisco   Steve